AWSTemplateFormatVersion: '2010-09-09'
Description: Photo Album Assignment 3

Resources:
  PhotosBucketCF:
    Type: AWS::S3::Bucket
    Properties:
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT]
            AllowedOrigins: ['*']

  FrontendBucketCF:
    Type: AWS::S3::Bucket
    Properties:
      WebsiteConfiguration:
        IndexDocument: index.html

  IndexPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: index-photos-cloudformation
      Runtime: python3.12
      Handler: index.handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/index-photos-role-09l9wx53'
      Code:
        ZipFile: |
          def handler(event, context):
            return {'statusCode': 200, 'body': 'ok'}
      Timeout: 60
      MemorySize: 256

  SearchPhotosFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: search-photos-cloudformation
      Runtime: python3.12
      Handler: index.handler
      Role: !Sub 'arn:aws:iam::${AWS::AccountId}:role/search-photos-role-ixytji9g'
      Code:
        ZipFile: |
          def handler(event, context):
            return {'statusCode': 200, 'body': 'ok'}
      Timeout: 60
      MemorySize: 256

  PhotoSearchAPICF:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: PhotoSearchAPI-CF2

Outputs:
  FrontendURL:
    Value: !GetAtt FrontendBucketCF.WebsiteURL
    Description: Frontend website URL
